name: ScottLarson
favicon: null
layout_spectrum: 0.9019
typography_spectrum: 0.25277
title: SCOTT LARSON
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9c9c9c'
    - '#353535'
    - '#cbcbcb'
  brandStrength: 0.5
  lightness: 0.6092719612643123
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
